### ISSUE TITLE
setup environment

### ISSUE THREAD

**Issue by Nazek-Altayeb** [Nazek-Altayeb/fun-times#1]
As the project owner i can setup and config the development environment so i can implement 

**Acceptance criteria**

- react project run successfully, app.js content is rendered.
- project is deployed and tested using Heruko.

**Tasks** 

- [x] install npm recent version,
- [x] create react project, run in the local env,
- [x] create github repository (fun times), create a roadmap project, and add issues to.
