### ISSUE TITLE
Create post

### ISSUE THREAD

**Issue by Nazek-Altayeb** [Nazek-Altayeb/fun-times#10]
As a **logged in user** I can **write** picnics suggestions so other pupils and teachers can **consider**.

**Acceptance criteria**
user can write and submit adventures posts, which include content and an image.

**Tasks**

- [x] create a new js file `PostCreateForm` , hold the form inputs with hooks that handle the inputs.
- [x] create style file , hold the css roles that reflect nice UI
- [x] add url to the `Navbar.js`
