### ISSUE TITLE
post visibility

### ISSUE THREAD

**Issue by Nazek-Altayeb** [Nazek-Altayeb/fun-times#13]
As a login user, I can specify whether the post is visible to all users or only the followers, so i can keep private.

**Tasks**

- [x] extend the create post form, add two options fields (private, public)
- [x] create hook to handle each choice
- [x] set a condition before submitting the post to the home page, the condition should result in having the post visible only to followers incase the post is private
