### ISSUE TITLE
add navigation bar

### ISSUE THREAD

**Issue by Nazek-Altayeb** [Nazek-Altayeb/fun-times#3]
As a **teacher / pupil** i can view the navbar from all pages, so i can navigate easily between pages

**Acceptance criteria**

- A Navbar consists of the following icons (Home , Sign in, Sign up)
- The Navbar has effects
- The header has a custom Logo.

**Tasks**

- [x] Add a component directory, and a NavBar.js file inside.
- [x] inside NavBar.js, create functional component, add navbar, use react bootstrap classes to costomize.
- [x] Add css style module for both App and NavBar components.
