### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by Nazek-Altayeb** [Nazek-Altayeb/fun-times#4]
**Goal**
As a website user, i can create an account, so i can be able to have full-access to all features.

**Acceptance**
User creates an account and redirected to the main page

**Tasks**

- [x] Create and add Signup styles in SignInUpForm.module.css.
- [x] Create a new page SignUpForm.
- [x] install axios to enable the front-end app  to call the backend, 
- [x] Create a file axiosDefaults , define the backend URL, export (axiosReq , axiosRes)
