### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Nazek-Altayeb** [Nazek-Altayeb/fun-times#5]
As a registered  user, i can login, so i can benefit my access priviliges.

**Acceptance criteria**

User login with his/her own credentials successfully.

**Tasks** 

- [x] Create a new file pages/auth/signInForm.js.
- [x] copy the boilerplate code given by CodeInstitute LMS, add a form using the React Bootstrap, the form should have two inputs (username, password), define the handleSubmit and handleChange functions.
- [x] add the signInForm to the App.js route.
