### ISSUE TITLE
Manage profile

### ISSUE THREAD

**Issue by Nazek-Altayeb** [Nazek-Altayeb/fun-times#7]
As a registered user, I can edit my profile, so I can update my information.

**Acceptance criteria**

Profile is editable, avatar can be changed, new information can be added `visited_city, activity, age, favourite_hoppy`

**Tasks**

- [x] create `ProfileEditForm` file, create form of all input fields that relate to the `Profile` model
- [x] define a hook that handle changes being done to the form input field
- [x] define a hook that handle submit of the form, this is done by appending the new values to the related object field.
